/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./../src/components/Domain/components/Account.vue')['default']
    AccountFormDialog: typeof import('./../src/components/Domain/components/AccountFormDialog.vue')['default']
    AccountList: typeof import('./../src/components/Domain/components/AccountList.vue')['default']
    Domain: typeof import('./../src/components/Domain/index.vue')['default']
    DomainBar: typeof import('./../src/components/Domain/components/DomainBar.vue')['default']
    Header: typeof import('./../src/components/Header.vue')['default']
    Tags: typeof import('./../src/components/Domain/components/Tags.vue')['default']
  }
}
