/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./../src/components/Domain/components/Account.vue')['default']
    AccountFormDialog: typeof import('./../src/components/Domain/components/AccountFormDialog.vue')['default']
    AccountList: typeof import('./../src/components/Domain/components/AccountList.vue')['default']
    Domain: typeof import('./../src/components/Domain/index.vue')['default']
    DomainBar: typeof import('./../src/components/Domain/components/DomainBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./../src/components/Tag/index.vue')['default']
    Tags: typeof import('./../src/components/Domain/components/Tags.vue')['default']
  }
}
